### ISSUE TITLE
PySCF for quantum chemistry

### ISSUE THREAD

**Issue by Le0nerdo** [aspuru-guzik-group/tequila#152]
PySCF is mentioned in the overview article and in some of the source code, but it does not seem to be supported currently. Because it is not mentioned in the readme and I failed to use I am assuming that it is not currently supported. Are there plans to support it again in the future? I am also wondering about the reason why it is not supported anymore.

**Comment by kottmanj** [comment]
Hi and thanks for the feedback.

PySCF is supported but not fully integrated. Currently you need to feed the one- and two-body integrals manually to the initialization. But then you have access to a range of it's methods. This is for example used in combination with directly determined orbitals (through madness) in order to compute standard energies (ccsd, ccsd(t), fci) with them. 

if you have the molecular integrals (two body terms in openfermion ordering) ready, you can use it like this
`mol = tq.Molecule(geometry="be 0.0 0.0 0.0", backend="pyscf", one_body_integrals=h, two_body_integrals=g, nuclear_repulsion=1.0, basis_set="dummy")`
and then for example
`mol.compute_energy("ccsd")`

if you have the two-body integrals as numpy array, you can switch between the orderings via
g = tq.chemistry.qc_base.NBodyTensor(elems=array, ordering='name')
g.reorder(to='name')
with name = ["openfermion", "mulliken", "dirac"] 

In the madness backend this is automatized for the classical methods. See for example here
https://github.com/aspuru-guzik-group/tequila-tutorials/blob/main/ChemistrySeparablePairAnsatz.ipynb

You are probably looking for something like
`mol = tq.Molecule(geometry="be 0.0 0.0 0.0", basis_set="sto-3g")`
that computes the integrals automatically through pyscf?
Currently that is not fully automatized, but I can look into it, if you need it.

**Comment by kottmanj** [comment]
Good news. Full support is integrated ;-)
Thanks for pushing me. Should have done that a long time ago.

Currently, you need to checkout and install from the `devel` branch, as the changes are not merged to the main branch yet.

Either 
```bash
git clone https://github.com/aspuru-guzik-group/tequila
cd tequila
git checkout devel
pip install -e .
```

or install directly
`pip install git+https://github.com/aspuru-guzik-group/tequila.git@devel`

The usage is the same as for the `psi4` backend.
E.g.
`mol = tq.Molecule(geometry="geomfile.xyz", basis_set="sto-3g")`

Let me know if you experience any troubles with it.

I will keep this issue open until the update has been merged to the main branch and released over PyPi.

**Comment by Le0nerdo** [comment]
Awesome!
I tried it out and did not find any problems.

**Comment by kottmanj** [comment]
Great. By now it's part of the main branch. Thanks for notifying
