### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by olgOk** [aspuru-guzik-group/tequila#19]
I have some questions/issues about the installation process.

First, it would be nice to get it installed via pip. 

Second, for some or other reasons I was not able to install qulacs on mac os. In the Quantum Backends you've mentioned Tequila can detect backends automatically. I have installed Cirq and Qiskit on the mac, however, it seems like Tequila looks for qulacs specifically and, because of that, installation fails. Can you please advice on this issue?

**Comment by kottmanj** [comment]
Hi olgOK

pip installation over PyPi cloud is planned. We are currently preparing for release. But pip installation from source should already be possible.

Regarding qulacs on Mac: There are some issues with apples clang compiler. It works however if you install gcc compilers (you can do that for example with homebrew or macports, you will need gcc and g++ version 7 or higher). There is another problem: The gcc and g++ commands are usually linked to the clang compilers you need to change that (alternatively you can install qulacs from source and change the gcc/g++ commands in the setup.py to the right ones on your system (often g++-X and gcc-X where X=7,8,9 depending what you installed before)

We currently try to force the qulacs installation since that is significantly faster than the others. You can however circumvent that by removing the qulacs entry from requirements.txt (you can add another simulator like cirq, qiskit or pyquil instead or install it seperately)

Regarding the other simulators:
It doesn't matter if they are installed at the point of the tequila installation, you can also install them at a later point. It is just important that you install them in the same python environment as tequila.

If you have tequila installed you can check which simulators were found within your environment with

import tequila as tq
tq.show_available_simulators()

Let me know if any of this worked.
Best wishes from Toronto

**Comment by olgOk** [comment]
Hi kotomanj,

Changing the gcc/g++ commands in the setup.py helped to solve to the problem and, finally, install qulacs, and tequila. 

Works!

Thanks for your help!
